algebra = {
 'Арифметическая прогрессия': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-posledovatelnosti-progressii-9139/arifmeticheskaia-progressiia-svoistva-arifmeticheskoi-progressii-9141',
 'Свойства корней': 'https://www.yaklass.ru/p/algebra/8-klass/funktciia-y-x-funktciia-kvadratnogo-kornia-y-x-9098/bazovye-svoistva-kvadratnykh-kornei-9100',
 'Степень': 'https://www.yaklass.ru/p/algebra/7-klass/svoistva-stepenei-s-naturalnym-pokazatelem-9095/bazovye-svoistva-stepenei-s-naturalnym-pokazatelem-9094',
 'Расположение графиков линейных функций': 'https://www.yaklass.ru/p/algebra/7-klass/lineinaia-funktciia-y-kx-m-9165/vzaimnoe-raspolozhenie-grafikov-lineinykh-funktcii-12121',
 'Геометрическая прогрессия': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-posledovatelnosti-progressii-9139/geometricheskaia-progressiia-svoistva-geometricheskoi-progressii-9142',
 'Деление одночленов': 'https://www.yaklass.ru/p/algebra/7-klass/odnochleny-slozhenie-i-vychitanie-umnozhenie-i-delenie-odnochlenov-10482/delenie-odnochlenov-9086',
 'Запись функции в виде у = f(x) ': 'https://www.yaklass.ru/p/algebra/7-klass/kvadratichnaia-funktciia-y-x-12253/zapis-funktcii-v-vide-u-f-x-12157',
 'Рациональные уравнения для решения задач': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratnye-uravneniia-11021/ispolzovanie-ratcionalnykh-uravnenii-dlia-resheniia-zadach-12479',
 'Системы рациональных уравнений для решения задач': 'https://www.yaklass.ru/p/algebra/9-klass/sistemy-uravnenii-ravnosilnye-preobrazovaniia-9129/ispolzovanie-sistem-ratcionalnykh-uravnenii-dlia-resheniia-zadach-12394',
 'Деление многочлена на одночлен': 'https://www.yaklass.ru/p/algebra/7-klass/mnogochleny-arifmeticheskie-deistviia-s-mnogochlenami-11002/kak-delit-mnogochlen-na-odnochlen-11004',
 'График функции y = f(x + l) + m': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratichnaia-funktciia-y-ax-funktciia-y-k-x-11012/kak-postroit-grafik-funktcii-y-f-x-l-m-11014',
 'График функции у = f(x + l)': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratichnaia-funktciia-y-ax-funktciia-y-k-x-11012/kak-postroit-grafik-funktcii-u-f-x-l-12266',
 'График функции у = f(x) + m': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratichnaia-funktciia-y-ax-funktciia-y-k-x-11012/kak-postroit-grafik-funktcii-u-f-x-m-12280',
 'Линейное неравенство': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/kak-reshat-lineinoe-neravenstvo-9126',
 'Сложение и вычитание алгебраических дробей с равными знаменателями': 'https://www.yaklass.ru/p/algebra/8-klass/algebraicheskie-drobi-arifmeticheskie-operatcii-nad-algebraicheskimi-drobi_-9085/kak-skladyvat-i-vychitat-algebraicheskie-drobi-s-ravnymi-znamenateliami-11011',
 'Сложение и вычитание алгебраических дробей с разными знаменателями': 'https://www.yaklass.ru/p/algebra/8-klass/algebraicheskie-drobi-arifmeticheskie-operatcii-nad-algebraicheskimi-drobi_-9085/kak-skladyvat-i-vychitat-algebraicheskie-drobi-s-raznymi-znamenateliami-11977',
 'Сложение и вычитание многочленов': 'https://www.yaklass.ru/p/algebra/7-klass/mnogochleny-arifmeticheskie-deistviia-s-mnogochlenami-11002/kak-skladyvat-i-vychitat-mnogochleny-9338',
 'Умножение многочлена на многочлен': 'https://www.yaklass.ru/p/algebra/7-klass/mnogochleny-arifmeticheskie-deistviia-s-mnogochlenami-11002/kak-umnozhat-mnogochlen-na-mnogochlen-9339',
 'Умножение многочлена на одночлен': 'https://www.yaklass.ru/p/algebra/7-klass/mnogochleny-arifmeticheskie-deistviia-s-mnogochlenami-11002/kak-umnozhat-mnogochlen-na-odnochlen-11003',
 'Умножение, деление и возведение в степень алгебраических дробей': 'https://www.yaklass.ru/p/algebra/8-klass/algebraicheskie-drobi-arifmeticheskie-operatcii-nad-algebraicheskimi-drobi_-9085/kak-umnozhat-delit-i-vozvodit-v-stepen-algebraicheskie-drobi-9091',
 'Квадратные уравнения': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratnye-uravneniia-11021/kakie-byvaiut-kvadratnye-uravneniia-9117',
 'Квадратичная функция  y = ax² + bx + c': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratichnaia-funktciia-y-ax-funktciia-y-k-x-11012/kvadratichnaia-funktciia-y-ax-bx-c-9108',
 'Квадратичная функция y =  ax² и её свойства. Парабола': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratichnaia-funktciia-y-ax-funktciia-y-k-x-11012/kvadratichnaia-funktciia-y-ax-i-ee-svoistva-parabola-11013',
 'Квадратичная функция y = x² и её график': 'https://www.yaklass.ru/p/algebra/7-klass/kvadratichnaia-funktciia-y-x-12253/kvadratichnaia-funktciia-y-x-i-ee-grafik-12139',
 'Координатная плоскость': 'https://www.yaklass.ru/p/algebra/7-klass/lineinaia-funktciia-y-kx-m-9165/koordinatnaia-ploskost-koordinaty-tochki-12117',
 'Координатная прямая': 'https://www.yaklass.ru/p/algebra/7-klass/matematicheskie-modeli-11008/koordinatnaia-priamaia-chislovye-promezhutki-11971',
 'Линейная функция y = kx + m': 'https://www.yaklass.ru/p/algebra/7-klass/lineinaia-funktciia-y-kx-m-9165/lineinaia-funktciia-y-kx-m-grafik-lineinoi-funktcii-9107',
 'Линейная функция y = kx': 'https://www.yaklass.ru/p/algebra/7-klass/lineinaia-funktciia-y-kx-m-9165/lineinaia-funktciia-y-kx-ee-svoistva-10997',
 'Линейное уравнение ax + by + c = 0': 'https://www.yaklass.ru/p/algebra/7-klass/lineinaia-funktciia-y-kx-m-9165/lineinoe-uravnenie-ax-by-c-0-grafik-lineinogo-uravneniia-12118',
 'Линейное уравнение с одной переменной': 'https://www.yaklass.ru/p/algebra/7-klass/matematicheskie-modeli-11008/lineinoe-uravnenie-s-odnoi-peremennoi-algoritm-resheniia-9113',
 'Математические модели реальных ситуаций': 'https://www.yaklass.ru/p/algebra/7-klass/matematicheskie-modeli-11008/matematicheskie-modeli-realnykh-situatcii-11969',
 'Математический язык': 'https://www.yaklass.ru/p/algebra/7-klass/matematicheskie-modeli-11008/matematicheskii-iazyk-11968',
 'Методы решения квадратных неравенств': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/metody-resheniia-kvadratnykh-neravenstv-9127',
 'Методы решения систем рациональных уравнений': 'https://www.yaklass.ru/p/algebra/9-klass/sistemy-uravnenii-ravnosilnye-preobrazovaniia-9129/metody-resheniia-sistem-ratcionalnykh-uravnenii-9131',
 'Множества и подмножества': 'https://www.yaklass.ru/p/algebra/9-klass/neravenstva-i-sistemy-neravenstv-9125/mnozhestva-i-podmnozhestva-obedinenie-i-peresechenie-mnozhestv-12443',
 'Множества натуральных чисел, целых чисел, рациональных чисел': 'https://www.yaklass.ru/p/algebra/8-klass/deistvitelnye-chisla-9092/mnozhestva-naturalnykh-chisel-tcelykh-chisel-ratcionalnykh-chisel-11990',
 'Множество действительных чисел': 'https://www.yaklass.ru/p/algebra/8-klass/deistvitelnye-chisla-9092/mnozhestvo-deistvitelnykh-chisel-i-ee-geometricheskaia-model-12419',
 'Множество рациональных чисел': 'https://www.yaklass.ru/p/algebra/8-klass/deistvitelnye-chisla-9092/mnozhestvo-ratcionalnykh-chisel-12344',
 'Модуль действительного числа': 'https://www.yaklass.ru/p/algebra/8-klass/funktciia-y-x-funktciia-kvadratnogo-kornia-y-x-9098/modul-deistvitelnogo-chisla-i-ego-geometricheskii-smysl-12427',
 'Определение числовой функции': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/opredelenie-chislovoi-funktcii-i-sposoby-ee-zadaniia-9178',
 'Относительная частота': 'https://www.yaklass.ru/p/algebra/9-klass/elementy-kombinatoriki-statistiki-i-teorii-veroiatnostei-10205/otnositelnaia-chastota-i-statisticheskaia-veroiatnost-sobytiia-12692',
 'Алгебраическая дробь': 'https://www.yaklass.ru/p/algebra/8-klass/algebraicheskie-drobi-arifmeticheskie-operatcii-nad-algebraicheskimi-drobi_-9085/poniatie-algebraicheskoi-drobi-11009',
 'Иррациональное число': 'https://www.yaklass.ru/p/algebra/8-klass/deistvitelnye-chisla-9092/poniatie-irratcionalnogo-chisla-12158',
 'Квадратный корень': 'https://www.yaklass.ru/p/algebra/8-klass/deistvitelnye-chisla-9092/poniatie-kvadratnogo-kornia-9099',
 'Многочлен': 'https://www.yaklass.ru/p/algebra/7-klass/mnogochleny-arifmeticheskie-deistviia-s-mnogochlenami-11002/poniatie-mnogochlena-privedenie-mnogochlena-k-standartnomu-vidu-9337',
 'Монотонность функции': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/poniatie-monotonnosti-funktcii-issledovanie-funktcii-na-monotonnost-12102',
 'Одночлен': 'https://www.yaklass.ru/p/algebra/7-klass/odnochleny-slozhenie-i-vychitanie-umnozhenie-i-delenie-odnochlenov-10482/poniatie-odnochlena-privedenie-odnochlena-k-standartnomu-vidu-11038',
 'Разложение многочленов на множители': 'https://www.yaklass.ru/p/algebra/7-klass/razlozhenie-mnogochlenov-na-mnozhiteli-sposoby-razlozheniia-11005/poniatie-razlozheniia-mnogochlenov-na-mnozhiteli-11533',
 'Системы линейных уравнений с двумя переменными': 'https://www.yaklass.ru/p/algebra/7-klass/reshenie-sistem-lineinykh-uravnenii-s-dvumia-peremennymi-10998/poniatie-sistemy-lineinykh-uravnenii-s-dvumia-peremennymi-12436',
 'Системы рациональных уравнений': 'https://www.yaklass.ru/p/algebra/9-klass/sistemy-uravnenii-ravnosilnye-preobrazovaniia-9129/poniatie-sistemy-ratcionalnykh-uravnenii-12393',
 'Степень с натуральным показателем': 'https://www.yaklass.ru/p/algebra/7-klass/svoistva-stepenei-s-naturalnym-pokazatelem-9095/poniatie-stepeni-s-naturalnym-pokazatelem-9093',
 'Степень с нулевым показателем': 'https://www.yaklass.ru/p/algebra/7-klass/svoistva-stepenei-s-naturalnym-pokazatelem-9095/poniatie-stepeni-s-nulevym-pokazatelem-12040',
 'Степени с отрицательным целым показателем': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/poniatie-stepeni-s-otritcatelnym-tcelym-pokazatelem-9096',
 'Тождество': 'https://www.yaklass.ru/p/algebra/7-klass/razlozhenie-mnogochlenov-na-mnozhiteli-sposoby-razlozheniia-11005/poniatie-tozhdestva-11540',
 'Числовая последовательность': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-posledovatelnosti-progressii-9139/poniatie-chislovoi-posledovatelnosti-sposoby-zadaniia-posledovatelnostei-11943',
 'Числовые промежутки': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/poniatie-chislovykh-promezhutkov-11024',
 'Преобразование иррациональных выражений': 'https://www.yaklass.ru/p/algebra/8-klass/funktciia-y-x-funktciia-kvadratnogo-kornia-y-x-9098/preobrazovanie-irratcionalnykh-vyrazhenii-11017',
 'Приближённые значения по недостатку': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/priblizhennye-znacheniia-po-nedostatku-po-izbytku-12434',
 'Применение основного свойства алгебраической дроби': 'https://www.yaklass.ru/p/algebra/8-klass/algebraicheskie-drobi-arifmeticheskie-operatcii-nad-algebraicheskimi-drobi_-9085/primenenie-osnovnogo-svoistva-algebraicheskoi-drobi-9090',
 'Применение разложения на множители для сокращения алгебраических дробей': 'https://www.yaklass.ru/p/algebra/7-klass/razlozhenie-mnogochlenov-na-mnozhiteli-sposoby-razlozheniia-11005/primenenie-razlozheniia-na-mnozhiteli-dlia-sokrashcheniia-algebraicheskik_-11448',
 'Теорема Виета': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratnye-uravneniia-11021/primenenie-teoremy-vieta-9116',
 'Применение формул сокращённого умножения': 'https://www.yaklass.ru/p/algebra/7-klass/mnogochleny-arifmeticheskie-deistviia-s-mnogochlenami-11002/primenenie-formul-sokrashchennogo-umnozheniia-9088',
 'Произведение одночленов и возведение одночлена в степень': 'https://www.yaklass.ru/p/algebra/7-klass/odnochleny-slozhenie-i-vychitanie-umnozhenie-i-delenie-odnochlenov-10482/proizvedenie-odnochlenov-i-vozvedenie-odnochlena-v-stepen-11040',
 'Разложение на множители. Вынесение общего множителя за скобки': 'https://www.yaklass.ru/p/algebra/7-klass/razlozhenie-mnogochlenov-na-mnozhiteli-sposoby-razlozheniia-11005/razlozhenie-na-mnozhiteli-vynesenie-obshchego-mnozhitelia-za-skobki-9089',
 'Разложение на множители. Формулы сокращённого умножения': 'https://www.yaklass.ru/p/algebra/7-klass/razlozhenie-mnogochlenov-na-mnozhiteli-sposoby-razlozheniia-11005/razlozhenie-na-mnozhiteli-ispolzovanie-formul-sokrashchennogo-umnozheniia-11007',
 'Разложение на множители. Различные приёмы': 'https://www.yaklass.ru/p/algebra/7-klass/razlozhenie-mnogochlenov-na-mnozhiteli-sposoby-razlozheniia-11005/razlozhenie-na-mnozhiteli-sochetanie-razlichnykh-priemov-11446',
 'Разложение на множители. Группировка': 'https://www.yaklass.ru/p/algebra/7-klass/razlozhenie-mnogochlenov-na-mnozhiteli-sposoby-razlozheniia-11005/razlozhenie-na-mnozhiteli-sposob-gruppirovki-11006',
 'Свойства основных функций': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/svoistva-osnovnykh-funktcii-9106',
 'Свойства числовых неравенств': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/svoistva-chislovykh-neravenstv-svoistva-neravenstv-odinakovogo-smysla-12298',
 'Система линейных уравнений': 'https://www.yaklass.ru/p/algebra/7-klass/reshenie-sistem-lineinykh-uravnenii-s-dvumia-peremennymi-10998/sistema-lineinykh-uravnenii-kak-matematicheskaia-model-12474',
 'Системы рациональных неравенств': 'https://www.yaklass.ru/p/algebra/9-klass/neravenstva-i-sistemy-neravenstv-9125/sistemy-ratcionalnykh-neravenstv-9130',
 'Сложение и вычитание подобных одночленов': 'https://www.yaklass.ru/p/algebra/7-klass/odnochleny-slozhenie-i-vychitanie-umnozhenie-i-delenie-odnochlenov-10482/slozhenie-i-vychitanie-podobnykh-odnochlenov-11039',
 'Способы решения квадратных уравнений': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratnye-uravneniia-11021/sposoby-resheniia-kvadratnykh-uravnenii-9115',
 'Стандартный вид положительного числа': 'https://www.yaklass.ru/p/algebra/8-klass/neravenstva-11023/standartnyi-vid-polozhitelnogo-chisla-12462',
 'Степенная функция с натуральным показателем': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/stepennaia-funktciia-s-naturalnym-pokazatelem-12044',
 'Степенная функция с отрицательным целым показателем': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/stepennaia-funktciia-s-otritcatelnym-tcelym-pokazatelem-12093',
 'Умножение и деление степеней с одинаковыми натуральными показателями': 'https://www.yaklass.ru/p/algebra/7-klass/svoistva-stepenei-s-naturalnym-pokazatelem-9095/umnozhenie-i-delenie-stepenei-s-odinakovymi-naturalnymi-pokazateliami-11945',
 'Упрощение рациональных выражений': 'https://www.yaklass.ru/p/algebra/8-klass/algebraicheskie-drobi-arifmeticheskie-operatcii-nad-algebraicheskimi-drobi_-9085/uproshchenie-ratcionalnykh-vyrazhenii-12036',
 'Упрощённая формула для решения квадратного уравнения': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratnye-uravneniia-11021/uproshchennaia-formula-dlia-resheniia-kvadratnogo-uravneniia-12487',
 'Функция y = k/x. Гипербола': 'https://www.yaklass.ru/p/algebra/8-klass/kvadratichnaia-funktciia-y-ax-funktciia-y-k-x-11012/funktciia-y-k-x-i-ee-svoistva-giperbola-9599',
 'Функция квадратного корня y = √x, её свойства и график': 'https://www.yaklass.ru/p/algebra/8-klass/funktciia-y-x-funktciia-kvadratnogo-kornia-y-x-9098/funktciia-kvadratnogo-kornia-y-x-ee-svoistva-i-grafik-9109',
 'Функция кубического корня': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/funktciia-kubicheskogo-kornia-12112',
 'Часто используемые степени': 'https://www.yaklass.ru/p/algebra/7-klass/svoistva-stepenei-s-naturalnym-pokazatelem-9095/chasto-ispolzuemye-stepeni-11983',
 'Числовые выражения': 'https://www.yaklass.ru/p/algebra/7-klass/matematicheskie-modeli-11008/chislovye-vyrazheniia-algebraicheskie-vyrazheniia-11967',
 'Чётные и нечётные функции': 'https://www.yaklass.ru/p/algebra/9-klass/chislovye-funktcii-svoistva-chislovykh-funktcii-9132/chetnye-i-nechetnye-funktcii-opredelenie-chetnosti-i-nechetnosti-9105',
 'Элементы комбинаторики': 'https://www.yaklass.ru/p/algebra/9-klass/elementy-kombinatoriki-statistiki-i-teorii-veroiatnostei-10205/elementy-kombinatoriki-kombinatornye-zadachi-12502',
 'Элементы статистики': 'https://www.yaklass.ru/p/algebra/9-klass/elementy-kombinatoriki-statistiki-i-teorii-veroiatnostei-10205/elementy-statistiki-metody-obrabotki-informatcii-10215',
 'Элементы теории вероятности': 'https://www.yaklass.ru/p/algebra/9-klass/elementy-kombinatoriki-statistiki-i-teorii-veroiatnostei-10205/elementy-teorii-veroiatnosti-nakhozhdenie-veroiatnosti-12691'}
geometry = {
 'Вектор в системе координат': 'https://www.yaklass.ru/p/geometria/9-klass/metod-koordinat-9887/vektor-v-sisteme-koordinat-9247',
 'Вписанная и описанная окружности': 'https://www.yaklass.ru/p/geometria/8-klass/okruzhnost-9230/vpisannaia-i-opisannaia-okruzhnosti-9244',
 'Второй и третий признаки равенства треугольников': 'https://www.yaklass.ru/p/geometria/7-klass/treugolniki-9112/vtoroi-i-tretii-priznaki-ravenstva-treugolnikov-9739',
 'Длина окружности. Площадь круга': 'https://www.yaklass.ru/p/geometria/9-klass/dlina-okruzhnosti-i-ploshchad-kruga-9241/dlina-okruzhnosti-ploshchad-kruga-9494',
 'Замечательные точки треугольника': 'https://www.yaklass.ru/p/geometria/8-klass/okruzhnost-9230/zamechatelnye-tochki-treugolnika-9279',
 'Измерение отрезков и углов': 'https://www.yaklass.ru/p/geometria/7-klass/nachalnye-geometricheskie-svedeniia-14930/izmerenie-otrezkov-i-uglov-9704',
 'Касательная и окружность': 'https://www.yaklass.ru/p/geometria/8-klass/okruzhnost-9230/kasatelnaia-i-okruzhnost-9242',
 'Ломаная': 'https://www.yaklass.ru/p/geometria/8-klass/chetyrekhugolniki-9229/lomanaia-vidy-lomanykh-mnogougolniki-10436',
 'Луч, угол, обозначение угла': 'https://www.yaklass.ru/p/geometria/7-klass/nachalnye-geometricheskie-svedeniia-14930/luch-ugol-oboznachenie-ugla-9658',
 'Медиана, биссектриса, высота треугольника': 'https://www.yaklass.ru/p/geometria/7-klass/treugolniki-9112/mediana-bissektrisa-vysota-treugolnika-9481',
 'Многогранники': 'https://www.yaklass.ru/p/geometria/9-klass/nachalnye-svedeniia-o-stereometrii-13313/mnogogranniki-osnovnye-formuly-dlia-raschetov-13314',
 'Окружность. Радиус': 'https://www.yaklass.ru/p/geometria/7-klass/treugolniki-9112/okruzhnost-radius-zadachi-na-postroenie-10433',
 'Параллелограмм. Свойства параллелограмма. Трапеция': 'https://www.yaklass.ru/p/geometria/8-klass/chetyrekhugolniki-9229/parallelogramm-svoistva-parallelogramma-trapetciia-9234',
 'Параллельный перенос и поворот': 'https://www.yaklass.ru/p/geometria/9-klass/dvizhenie-10434/parallelnyi-perenos-i-povorot-9251',
 'Первый признак равенства треугольников': 'https://www.yaklass.ru/p/geometria/7-klass/treugolniki-9112/pervyi-priznak-ravenstva-treugolnikov-9122',
 'Перпендикулярные прямые': 'https://www.yaklass.ru/p/geometria/7-klass/nachalnye-geometricheskie-svedeniia-14930/perpendikuliarnye-priamye-smezhnye-i-vertikalnye-ugly-9886',
 'Многоугольник': 'https://www.yaklass.ru/p/geometria/8-klass/ploshchadi-figur-9235/ploshchad-mnogougolnika-svoistva-ploshchadei-9237',
 'Подобные треугольники. Пропорциональные отрезки': 'https://www.yaklass.ru/p/geometria/8-klass/podobnye-treugolniki-9236/podobnye-treugolniki-proportcionalnye-otrezki-9524',
 'Вектор': 'https://www.yaklass.ru/p/geometria/9-klass/vektory-9232/poniatie-vektora-vidy-vektorov-9233',
 'Симметрия': 'https://www.yaklass.ru/p/geometria/9-klass/dvizhenie-10434/poniatie-dvizheniia-simmetriia-10437',
 'Правила сложения и вычитания векторов': 'https://www.yaklass.ru/p/geometria/9-klass/vektory-9232/pravila-slozheniia-i-vychitaniia-vektorov-9239',
 'Правильные многоугольники': 'https://www.yaklass.ru/p/geometria/9-klass/dlina-okruzhnosti-i-ploshchad-kruga-9241/pravilnye-mnogougolniki-9246',
 'Признаки параллельности двух прямых. Свойства параллельных прямых. Аксиома параллельных прямых': 'https://www.yaklass.ru/p/geometria/7-klass/parallelnye-priamye-9124/priznaki-parallelnosti-dvukh-priamykh-svoistva-parallelnykh-priamykh-aksio_-9228',
 'Признаки подобия треугольников': 'https://www.yaklass.ru/p/geometria/8-klass/podobnye-treugolniki-9236/priznaki-podobiia-treugolnikov-9525',
 'Применение подобия. Решение задач': 'https://www.yaklass.ru/p/geometria/8-klass/podobnye-treugolniki-9236/primenenie-podobiia-reshenie-zadach-9482',
 'Проекция вектора на ось': 'https://www.yaklass.ru/p/geometria/9-klass/vektory-9232/proektciia-vektora-na-os-9249',
 'Прямая, отрезок, точки': 'https://www.yaklass.ru/p/geometria/7-klass/nachalnye-geometricheskie-svedeniia-14930/priamaia-otrezok-tochki-9703',
 'Прямоугольник, квадрат. Признаки прямоугольника и квадрата. Ромб': 'https://www.yaklass.ru/p/geometria/8-klass/chetyrekhugolniki-9229/priamougolnik-kvadrat-priznaki-priamougolnika-i-kvadrata-romb-9231',
 'Прямоугольный треугольник. Свойства. Признаки равенства': 'https://www.yaklass.ru/p/geometria/7-klass/sootnoshenie-mezhdu-storonami-i-uglami-treugolnika-9155/priamougolnyi-treugolnik-svoistva-priznaki-ravenstva-9175',
 'Расстояние от точки до прямой. Построение треугольника по трём элементам': 'https://www.yaklass.ru/p/geometria/7-klass/sootnoshenie-mezhdu-storonami-i-uglami-treugolnika-9155/rasstoianie-ot-tochki-do-priamoi-postroenie-treugolnika-po-trem-elementam-12420',
 'Решение простейших задач в координатах': 'https://www.yaklass.ru/p/geometria/9-klass/metod-koordinat-9887/reshenie-prosteishikh-zadach-v-koordinatakh-9250',
 'Синус, косинус, тангенс угла': 'https://www.yaklass.ru/p/geometria/9-klass/sootnosheniia-mezhdu-storonami-i-uglami-treugolnika-skaliarnoe-proizvedeni_-9222/sinus-kosinus-tangens-ugla-9280',
 'Скалярное произведение векторов. Свойства': 'https://www.yaklass.ru/p/geometria/9-klass/sootnosheniia-mezhdu-storonami-i-uglami-treugolnika-skaliarnoe-proizvedeni_-9222/skaliarnoe-proizvedenie-vektorov-svoistva-9526',
 'Соотношения между сторонами и углами треугольника': 'https://www.yaklass.ru/p/geometria/9-klass/sootnosheniia-mezhdu-storonami-i-uglami-treugolnika-skaliarnoe-proizvedeni_-9222/sootnosheniia-mezhdu-storonami-i-uglami-treugolnika-9281',
 'Сравнение отрезков и углов': 'https://www.yaklass.ru/p/geometria/7-klass/nachalnye-geometricheskie-svedeniia-14930/sravnenie-otrezkov-i-uglov-bissektrisa-12147',
 'Сумма углов треугольника': 'https://www.yaklass.ru/p/geometria/7-klass/sootnoshenie-mezhdu-storonami-i-uglami-treugolnika-9155/summa-uglov-treugolnika-vidy-treugolnikov-9171',
 'Теорема Пифагора': 'https://www.yaklass.ru/p/geometria/8-klass/ploshchadi-figur-9235/teorema-pifagora-dokazatelstvo-9225',
 'Теорема о соотношениях между сторонами и углами треугольника': 'https://www.yaklass.ru/p/geometria/7-klass/sootnoshenie-mezhdu-storonami-i-uglami-treugolnika-9155/teorema-o-sootnosheniiakh-mezhdu-storonami-i-uglami-treugolnika-9738',
 'Тригонометрические функции острого угла прямоугольного треугольника': 'https://www.yaklass.ru/p/geometria/8-klass/podobnye-treugolniki-9236/trigonometricheskie-funktcii-ostrogo-ugla-priamougolnogo-treugolnika-9226',
 'Умножение векторов на число': 'https://www.yaklass.ru/p/geometria/9-klass/vektory-9232/umnozhenie-vektorov-na-chislo-9245',
 'Уравнение окружности и прямой': 'https://www.yaklass.ru/p/geometria/9-klass/metod-koordinat-9887/uravnenie-okruzhnosti-uravnenie-priamoi-12247',
 'Формулы площадей параллелограмма, треугольника и трапеции': 'https://www.yaklass.ru/p/geometria/8-klass/ploshchadi-figur-9235/formuly-ploshchadei-parallelogramma-treugolnika-i-trapetcii-9238',
 'Центральные и вписанные углы': 'https://www.yaklass.ru/p/geometria/8-klass/okruzhnost-9230/tcentralnye-i-vpisannye-ugly-svoistvo-peresekaiushchikhsia-khord-okruzhnos_-9243',
 'Цилиндр. Конус. Сфера': 'https://www.yaklass.ru/p/geometria/9-klass/nachalnye-svedeniia-o-stereometrii-13313/tcilindr-konus-sfera-13315'}

informatics = {
 'Алгоритм. Команда присваивания': 'https://www.yaklass.ru/p/informatika/8-klass/osnovy-algoritmizatcii-14923/algoritm-komanda-prisvaivaniia-13978',
 'Алгоритмические конструкции': 'https://www.yaklass.ru/p/informatika/8-klass/osnovy-algoritmizatcii-14923/algoritmicheskie-konstruktcii-13987',
 'Базы данных': 'https://www.yaklass.ru/p/informatika/9-klass/modelirovanie-i-formalizatciia-13598/bazy-dannykh-6639462',
 'Ввод графической информации в компьютер': 'https://www.yaklass.ru/p/informatika/5-klass/kompiuternaia-grafika-12074/vvod-graficheskoi-informatcii-v-kompiuter-14364',
 'Виды памяти компьютера': 'https://www.yaklass.ru/p/informatika/5-klass/khranenie-informatcii-12071/vidy-pamiati-kompiutera-12279',
 'Визуализация данных в электронных таблицах': 'https://www.yaklass.ru/p/informatika/9-klass/obrabotka-chislovoi-informatcii-13600/vizualizatciia-dannykh-v-elektronnykh-tablitcakh-13734',
 'Вредоносное программное обеспечение': 'https://www.yaklass.ru/p/informatika/7-klass/kompiuter-kak-universalnoe-ustroistvo-dlia-raboty-s-informatciei-13602/vredonosnoe-programmnoe-obespechenie-6749705',
 'Вспомогательные алгоритмы на языке Pascal': 'https://www.yaklass.ru/p/informatika/9-klass/algoritmizatciia-i-programmirovanie-14692/vspomogatelnye-algoritmy-na-iazyke-pascal-6650420',
 'Вычисления в электронных таблицах. Ссылки, функции': 'https://www.yaklass.ru/p/informatika/9-klass/obrabotka-chislovoi-informatcii-13600/vychisleniia-v-elektronnykh-tablitcakh-ssylki-funktcii-13731',
 'Глобальная сеть Интернет': 'https://www.yaklass.ru/p/informatika/9-klass/kommunikatcionnye-tekhnologii-13601/globalnaia-set-internet-13330',
 'Графические редакторы': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-graficheskoi-informatcii-13934/graficheskie-redaktory-13706',
 'Графический редактор MS Paint': 'https://www.yaklass.ru/p/informatika/5-klass/kompiuternaia-grafika-12074/graficheskii-redaktor-ms-paint-11933',
 'Изображения на экране монитора': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-graficheskoi-informatcii-13934/izobrazheniia-na-ekrane-monitora-13704',
 'Интерфейс. Виды интерфейсов': 'https://www.yaklass.ru/p/informatika/7-klass/kompiuter-kak-universalnoe-ustroistvo-dlia-raboty-s-informatciei-13602/interfeis-vidy-interfeisov-6764939',
 'Информационный объём текста (повторение)': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-tekstovoi-informatcii-14582/informatcionnyi-obem-teksta-povtorenie-13826',
 'Информация и действия с информацией': 'https://www.yaklass.ru/p/informatika/7-klass/informatciia-i-informatcionnye-protcessy-14542/informatciia-i-deistviia-s-informatciei-6683201',
 'Как мы получаем информацию? Виды информации': 'https://www.yaklass.ru/p/informatika/5-klass/informatciia-vokrug-nas-12068/kak-my-poluchaem-informatciiu-vidy-informatcii-12087',
 'Клавиатура и её использование': 'https://www.yaklass.ru/p/informatika/5-klass/vvod-informatcii-v-pamiat-kompiutera-12069/klaviatura-i-ee-ispolzovanie-11936',
 'Кодирование и декодирование информации': 'https://www.yaklass.ru/p/informatika/5-klass/kodirovanie-informatcii-12645/kodirovanie-i-dekodirovanie-informatcii-13837',
 'Компьютерная графика. Сферы применения': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-graficheskoi-informatcii-13934/kompiuternaia-grafika-sfery-primeneniia-13705',
 'Компьютерное представление чисел': 'https://www.yaklass.ru/p/informatika/8-klass/matematicheskie-osnovy-informatiki-13971/kompiuternoe-predstavlenie-chisel-6597847',
 'Линейные алгоритмы в Паскаль': 'https://www.yaklass.ru/p/informatika/8-klass/nachala-programmirovaniia-14963/lineinye-algoritmy-v-paskal-14019',
 'Массивы в Pascal': 'https://www.yaklass.ru/p/informatika/9-klass/algoritmizatciia-i-programmirovanie-14692/massivy-v-pascal-6650418',
 'Начальные сведения о языке программирования Паскаль': 'https://www.yaklass.ru/p/informatika/8-klass/nachala-programmirovaniia-14963/nachalnye-svedeniia-o-iazyke-programmirovaniia-paskal-14000',
 'Обзор электронных таблиц': 'https://www.yaklass.ru/p/informatika/9-klass/obrabotka-chislovoi-informatcii-13600/obzor-elektronnykh-tablitc-13530',
 'Обобщение. Способы кодирования информации': 'https://www.yaklass.ru/p/informatika/7-klass/informatciia-i-informatcionnye-protcessy-14542/obobshchenie-sposoby-kodirovaniia-informatcii-6731943',
 'Общие сведения о системах счисления': 'https://www.yaklass.ru/p/informatika/8-klass/matematicheskie-osnovy-informatiki-13971/obshchie-svedeniia-o-sistemakh-schisleniia-6593963',
 'Операторы ввода и вывода данных': 'https://www.yaklass.ru/p/informatika/8-klass/nachala-programmirovaniia-14963/operatory-vvoda-i-vyvoda-dannykh-14004',
 'Память компьютера': 'https://www.yaklass.ru/p/informatika/7-klass/kompiuter-kak-universalnoe-ustroistvo-dlia-raboty-s-informatciei-13602/pamiat-kompiutera-6757690',
 'Программа для создания презентаций PowerPoint 2010': 'https://www.yaklass.ru/p/informatika/7-klass/multimedia-13638/programma-dlia-sozdaniia-prezentatcii-powerpoint-2010-12084',
 'Программное обеспечение ПК': 'https://www.yaklass.ru/p/informatika/7-klass/kompiuter-kak-universalnoe-ustroistvo-dlia-raboty-s-informatciei-13602/programmnoe-obespechenie-pk-6741828',
 'Программы для компьютерного перевода и распознавания текстов ': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-tekstovoi-informatcii-14582/programmy-dlia-kompiuternogo-perevoda-i-raspoznavaniia-tekstov-13825',
 'Разветвляющиеся алгоритмы': 'https://www.yaklass.ru/p/informatika/8-klass/nachala-programmirovaniia-14963/razvetvliaiushchiesia-algoritmy-14303',
 'Разработка Web-сайта': 'https://www.yaklass.ru/p/informatika/9-klass/kommunikatcionnye-tekhnologii-13601/razrabotka-web-saita-13782',
 'Создание документов с помощью текстовых редакторов': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-tekstovoi-informatcii-14582/sozdanie-dokumentov-s-pomoshchiu-tekstovykh-redaktorov-13822',
 'Состав сети Интернет. Обмен данными': 'https://www.yaklass.ru/p/informatika/9-klass/kommunikatcionnye-tekhnologii-13601/sostav-seti-internet-obmen-dannymi-13749',
 'Списки, таблицы и графика в текстовых документах': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-tekstovoi-informatcii-14582/spiski-tablitcy-i-grafika-v-tekstovykh-dokumentakh-13824',
 'Технологии создания текстовых документов': 'https://www.yaklass.ru/p/informatika/7-klass/obrabotka-tekstovoi-informatcii-14582/tekhnologii-sozdaniia-tekstovykh-dokumentov-13819',
 'Устройство компьютера': 'https://www.yaklass.ru/p/informatika/7-klass/kompiuter-kak-universalnoe-ustroistvo-dlia-raboty-s-informatciei-13602/ustroistvo-kompiutera-6756503',
 'Файлы и файловые системы': 'https://www.yaklass.ru/p/informatika/7-klass/kompiuter-kak-universalnoe-ustroistvo-dlia-raboty-s-informatciei-13602/faily-i-failovye-sistemy-6744044',
 'Циклы': 'https://www.yaklass.ru/p/informatika/8-klass/nachala-programmirovaniia-14963/tcikly-14349',
 'Цифровые данные. Двоичное кодирование': 'https://www.yaklass.ru/p/informatika/7-klass/informatciia-i-informatcionnye-protcessy-14542/tcifrovye-dannye-dvoichnoe-kodirovanie-6699592',
 'Элементы алгебры логики': 'https://www.yaklass.ru/p/informatika/8-klass/matematicheskie-osnovy-informatiki-13971/elementy-algebry-logiki-6617745'}